### ISSUE TITLE
Result showing as micro when its actually nano

### ISSUE THREAD

**Issue by icetbr** [icebob/benchmarkify#8]
Hello there fellow iceman. I think you have a problem in your stats. Humanize expects milli as a value. This is milli:

benchmarkify/index.js:111
```
const duration = diff[0] + diff[1] / 1e9;

_.assign(this.stat, {
	duration,
	avg: duration / count,
	rps: count / duration
});
```

When you multiply by 1000 you turn it into micro:

benchmarkify/index.js:507
```
"  (avg: " + humanize.short(test.stat.avg * 1000) + ")"
```

This gives a false result.

Really love the simplicity, the defaults and the beautiful output of your project. Keep it up!

**Comment by icebob** [comment]
The value is correct. The `avg` value is in seconds, so it's multiplied by 1000 for milliseconds.
